---
- name: "Directory Exists | {{ mongodb_runtime_root }}"
  file:
    state: directory
    path: "{{ mongodb_runtime_root }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - mongodb

- name: Directory Exists | /var/lib/mongodb
  file:
    state: directory
    path: /var/lib/mongodb
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0755
  tags:
    - permissions
    - logging
    - mongo

- name: Configure | MongoDB | pidfilepath
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *pidfilepath ?\='
    line: "pidfilepath = {{ mongodb_pidfile_path }}"
  notify: service | mongodb | reloaded
  tags:
    - configuration
    - precise-configuration
    - pidfile
    - monitoring
    - using-monit

- name: Configure | MongoDB | mongodb auth enabled
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *auth ?\='
    line: 'auth = true'
  when: mongodb_auth_enabled
  notify: service | mongodb | reloaded
  tags:
    - configuration
    - precise-configuration
    - mongodb

- name: Configure | MongoDB | accepts external connections
  lineinfile:
    state: absent
    dest: /etc/mongod.conf
    regexp: '^#* *bind_ip'
  when: mongodb_accepts_external_connections
  notify: service | mongodb | reloaded
  tags:
    - configuration
    - precise-configuration
    - mongodb
