---
- name: Configure | MongoDB | mongodb auth enabled
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *auth ?\='
    line: 'auth = true'
  when: mongodb_auth_enabled
  notify: Reload Service | mongodb
  tags:
    - configuration
    - precise-configuration
    - mongodb

- name: Configure | MongoDB | accepts external connections
  lineinfile:
    state: absent
    dest: /etc/mongod.conf
    regexp: '^#* *bind_ip'
  when: mongodb_accepts_external_connections
  notify: Reload Service | mongodb
  tags:
    - configuration
    - precise-configuration
    - mongodb
