---
- name: Configure | MongoDB 
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *auth ?\='
    line: 'auth = true'
  notify: Reload Service | mongodb
  tags:
    - configuration
    - precise-configuration
    - mongodb

- name: Configure | MongoDB  
  lineinfile:
    state: absent
    dest: /etc/mongod.conf
    regexp: '^#* *bind_ip'
  notify: Reload Service | mongodb
  tags:
    - configuration
    - precise-configuration
    - mongodb
  when: mongodb_accepts_external_connections
