---
- name: "Directory Exists | {{ mongodb_runtime_root }}"
  file:
    state: directory
    path: "{{ mongodb_runtime_root }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0775
  when: mongodb_set_permissions
  tags:
    - directory-structure
    - runtime-data
    - mongodb

- name: Directory Exists | /var/lib/mongodb
  file:
    state: directory
    path: /var/lib/mongodb
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0755
  when: mongodb_set_permissions
  tags:
    - permissions
    - logging
    - mongo

- name: "Directory Exists | /data/db"
  file:
    state: directory
    path: /data/db
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - mongodb

- name: Configure | MongoDB | pidfilepath
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *processManagement:'
    line: "processManagement: \n  pidFilePath: {{ mongodb_pidfile_path }}"
  notify: service | mongodb | reloaded
  tags:
    - configuration
    - precise-configuration
    - pidfile
    - monitoring

- name: Configure | MongoDB | pidfilepath
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *pidFilePath:'
    line: "  pidFilePath: {{ mongodb_pidfile_path }}"
  notify: service | mongodb | reloaded
  tags:
    - configuration
    - precise-configuration
    - pidfile
    - monitoring


- name: Configure | MongoDB | accepts external connections
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *bindIp:'
    line: "  bindIp: 0.0.0.0"
  when: mongodb_accepts_external_connections
  notify: service | mongodb | reloaded
  tags:
    - configuration
    - precise-configuration
    - mongodb
