---
- name: Configure Mongo | Import the public key used by the package management system.
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80 
    id: EA312927
    state: present

- name: Configure Mongo | Create a list file for MongoDB.
  apt_repository: 
    repo: 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' 
    state: present

- name: Install Packages | apt
  apt: 
    pkg: "{{ item }}"
    state: present 
    update_cache: yes
  with_items:
    - mongodb-org-server
  when: mongodb_server

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - mongodb-org-shell
  when: mongodb_client

- name: Create Database User
  mongodb_user:
    database: "{{ database_name | default(project) }}"
    name: "{{ database_username | default(project) }}"
    password: "{{ database_password | mandatory }}"
  when: mongodb_server and mongodb_auth_enabled
