---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - mongodb-org-server
  when: mongodb_server

- name: Service Stopped | mongodb
  service:
    name: mongod
    state: stopped
  when: mongodb_server
  tags:
    - disruptive

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - mongodb-org-shell
  when: mongodb_client
