---
- name: Configure | MongoDB | logpath 
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *logpath ?\='
    line: "logpath = {{ mongodb_log_path }}"
  notify: Reload Service | mongodb
  tags:
    - configuration
    - precise-configuration
    - logging
    - mongodb

- name: Configure | MongoDB | logappend
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *logappend ?\='
    line: 'logappend = true'
  notify: Reload Service | mongodb
  tags:
    - configuration
    - precise-configuration
    - logging
    - mongodb
