---
- name: "Directory Exists | {{ mongodb_runtime_root }}"
  file:
    state: directory
    path: "{{ mongodb_runtime_root }}"
    owner: "{{ mongodb_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - logging
    - mongodb

- name: Upload Config | monit | mongodb
  template:
    src: etc/monit/conf.d/mongodb
    dest: /etc/monit/conf.d/mongodb
  notify: Reload Service | monit
  tags:
    - configuration
    - template-configuration
    - using-monit
    - mongodb

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Configure | MongoDB | pidfilepath
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *pidfilepath ?\='
    line: "pidfilepath = {{ mongodb_pidfile_path }}"
  notify: Reload Service | mongodb
  tags:
    - configuration
    - precise-configuration
    - pidfile
    - monitoring
    - using-monit
