---
- name: "Directory Exists | {{ mongodb_runtime_root }}"
  file:
    state: directory
    path: "{{ mongodb_runtime_root }}"
    owner: "{{ mongodb_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - logging
    - mongodb

- name: Configure | MongoDB | pidfilepath
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    regexp: '^#* *pidfilepath ?\='
    line: "pidfilepath = {{ mongodb_pidfile_path }}"
  notify: Reload Service | mongodb
  tags:
    - configuration
    - precise-configuration
    - pidfile
    - monitoring
    - using-monit
