---
- name: Import Signing Key | mongodb
  apt_key:
    state: present
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: '7F0CEB10'

- name: Import Repository | mongodb
  apt_repository:
    state: present
    repo: 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
  notify: Update Package Cache

- name: Trigger All Callbacks
  meta: flush_handlers
