---
- name: Reload Service | monit
  command: monit reload
  tags:
    - using-monit

- name: Reload Service | mongodb
  monit:
    state: restarted
    name: mongodb
  tags:
    - using-monit
    - disruptive
